from importes.paginas import Inicio
from importes.paginas import First_page
from importes.paginas import Pagina_tiendas
from importes.paginas import Pagina_empleados
from importes.paginas import Pagina_productos
from importes.paginas import Pagina_pedidos
from importes.paginas import Pagina_compras
from importes.paginas import Pagina_busqueda
from importes.bdd import init_database
